---
admin_email: infrastructure@pycon.ca
dbname: pycon2016
dbuser: symposion

letsencrypt_domains:
  - portland.pynorth.org
  - pycon.ca
  - www.pycon.ca
  - 2012.pycon.ca
  - 2013.pycon.ca
  - 2015.pycon.ca
  - 2016.pycon.ca

users:
  - username: pdm
    github_username: pdmccormick
  - username: myles
    github_username: myles
  - username: terry
    github_username: onebit0fme
  - username: dhoffman
    github_username: dhoffman34