---
admin_email: infrastructure@pycon.ca

letsencrypt_domains:
  - portland.pynorth.org
  - 2012.pycon.ca

users:
  - username: pdm
    github_username: pdmccormick
  - username: myles
    github_username: myles
