---

- name: Install nginx
  apt:
    pkg: "{{ item }}"
    state: installed
  become: true
  with_items:
    - nginx
  tags: dependencies

- name: Create the directory for the websites
  become: true
  file:
    path: "/srv/www/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - pycon.ca/2016
    - pycon.ca/staging.2016
    - pycon.ca/2015
    - pycon.ca/2013
    - pycon.ca/2012
    - pycon.ca/www
    - pynorth.org/portland

- name: Create the logs directory for the websites
  become: true
  file:
    path: "/srv/www/{{ item }}/logs"
    state: directory
    mode: 0755
  with_items:
    - pycon.ca/2016
    - pycon.ca/staging.2016
    - pycon.ca/2015
    - pycon.ca/2013
    - pycon.ca/2012
    - pycon.ca/www
    - pynorth.org/portland

- name: Create the html directory for the websites
  become: true
  file:
    path: "/srv/www/{{ item }}/html"
    state: directory
    mode: 0755
    owner: deploy
    group: deploy
  with_items:
    - pycon.ca/2016
    - pycon.ca/staging.2016
    - pycon.ca/2015
    - pycon.ca/2013
    - pycon.ca/2012
    - pycon.ca/www
    - pynorth.org/portland

- name: Copy Let's Encrypt config file
  become: true
  copy: src=etc_nginx_letsencrypt.conf dest=/etc/nginx/letsencrypt.conf
  notify: restart nginx

- name: Copy nginx server configs
  copy: src={{ item.template }} dest=/etc/nginx/sites-enabled/{{ item.file }}
  become: true
  with_items:
    - template: etc_nginx_sites-enabled-pycon.ca-www.conf
      file: pycon.ca-www
    - template: etc_nginx_sites-enabled-pycon.ca-2016.conf
      file: pycon.ca-2016
    - template: etc_nginx_sites-enabled-pycon.ca-2015.conf
      file: pycon.ca-2015
    - template: etc_nginx_sites-enabled-pycon.ca-2013.conf
      file: pycon.ca-2013
    - template: etc_nginx_sites-enabled-pycon.ca-2012.conf
      file: pycon.ca-2012
    - template: etc_nginx_sites-enabled-pynorth.org-portland.conf
      file: pynorth.org-portland
    - template: etc_nginx_sites-enabled-no-default.conf
      file: xxx-default
  notify: restart nginx

- include: h5bp.yml tags=h5bp
