---

- name: Update apt cache
  apt: update_cache=yes
  become: true
  tags:
    - dependencies

- name: Upgrade all safe packages
  apt: upgrade=safe
  become: true
  tags:
    - dependencies

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=installed
  become: true
  with_items:
    - apticron
    - build-essential
    - git
    - htop
    - iftop
    - iotop
    - mosh
    - python-software-properties
    - unattended-upgrades
    - vim
    - bc
  tags:
    - dependencies

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf
  become: true

- include: security.yml tags=security
- include: ufw.yml tags=ufw
