---

- name: Postgres client authentication configuration file
  template: src=pg_hba.conf dest=/etc/postgresql/9.5/main/pg_hba.conf
  become: true
  notify:
    - reload pg config

- name: Postgres configuration
  template: src=postgresql.conf dest=/etc/postgresql/9.5/main/postgresql.conf
  become: true
  notify:
    - restart postgres

- name: Ensure database for Django app
  postgresql_db: name={{dbname}} login_user=deploy

- name: Ensure Django has access to the database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpass}} priv=ALL login_user=deploy
