---

- name: Clone Let's Encrypt repository
  become: true
  git:
    repo: https://github.com/letsencrypt/letsencrypt
    dest: /opt/letsencrypt
    force: yes
  tags: letsencrypt

- name: Create Let's Encrypt config directory
  become: true
  file:
    path: /etc/letsencrypt
    state: directory
  tags: letsencrypt

- name: Copy over the Let's Encrypt renew script
  become: true
  copy:
    src: etc_letsencrypt_le-renew-webroot.sh
    dest: /etc/letsencrypt/le-renew-webroot
    mode: "u=rwx,g=r,o=r"
  tags: letsencrypt

- name: Copy over the Let's Encrypt config
  become: true
  template:
    src: le-renew-webroot.ini.j2
    dest: /etc/letsencrypt/le-renew-webroot.ini
  tags: letsencrypt

- name: Generate the Let's Encrypt certificate
  become: true
  command: /opt/letsencrypt/letsencrypt-auto certonly -a webroot --agree-tos --renew-by-default --config /etc/letsencrypt/le-renew-webroot.ini
  args:
    creates: /etc/letsencrypt/live/portland.pynorth.org
  tags: letsencrypt

- name: Setup a cron job to renew Let's Encrypt certificate
  become: true
  cron:
    name: "renew letsencrypt certificate"
    minute: 30
    hour: 2
    weekday: 1
    user: "root"
    job: "/etc/letsencrypt/le-renew-webroot >> /var/log/le-renewal.log"
    cron_file: letsencrypt-renew
  tags: letsencrypt
